# Generated by Django 5.0 on 2023-12-29 12:15

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(default=datetime.datetime(2023, 12, 29, 15, 15, 37, 301229))),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.basemodel')),
                ('category_name', models.TextField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
            bases=('course.basemodel',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.basemodel')),
                ('course_type', models.CharField(choices=[('REC', 'Recorded Course'), ('LIV', 'Live Session'), ('WEB', 'Webinar'), ('TRA', 'Learning Track')], default='REC', max_length=3)),
                ('title', models.TextField(default='archived course', max_length=80)),
                ('sub_title', models.TextField(default='archived course', max_length=120)),
                ('course_thumb', models.ImageField(upload_to='course_thumbnails')),
                ('course_trailer', models.FileField(null=True, upload_to='course_trailer', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('language', models.CharField(choices=[('AR', 'Arabic'), ('EN', 'English'), ('TR', 'Turkish')], default='AR', max_length=2)),
                ('duration', models.DurationField(help_text='HH:MM:SS')),
                ('description', models.TextField(max_length=1000)),
                ('price', models.IntegerField(help_text='$$')),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.category')),
            ],
            bases=('course.basemodel',),
        ),
    ]
